version: '3.8'

services:
  #mysql:
   # image: mysql:8.0
    #container_name: upi-mysql
    #environment:
     # MYSQL_ROOT_PASSWORD: root
      #MYSQL_USER: upi_user
      #MYSQL_PASSWORD: upi_pass
    #ports:
     # - "3306:3306"
    #volumes:
    #  - mysql_data:/var/lib/mysql
    #networks:
    #  - upi-network

  redis:
    image: redis:7.0-alpine
    container_name: upi-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis_pass
    networks:
      - upi-network

  mongodb:
    image: mongo:6.0
    container_name: upi-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    ports:
      - "27017:27017"
    networks:
      - upi-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: upi-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - upi-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: upi-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - upi-network

volumes:
  mysql_data:

networks:
  upi-network:
    driver: bridge
